# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'carUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget


class Ui_Car(QWidget):
    def setupUi(self):
        self.setObjectName("Car")
        self.resize(444, 567)
        self.groupBox_device_information = QtWidgets.QGroupBox(self)
        self.groupBox_device_information.setGeometry(QtCore.QRect(10, 10, 421, 131))
        self.groupBox_device_information.setObjectName("groupBox_device_information")
        self.textEdit_all_devices_information = QtWidgets.QTextEdit(self.groupBox_device_information)
        self.textEdit_all_devices_information.setGeometry(QtCore.QRect(10, 20, 401, 101))
        self.textEdit_all_devices_information.setObjectName("textEdit_all_devices_information")
        self.groupBox_set_battery_threshold = QtWidgets.QGroupBox(self)
        self.groupBox_set_battery_threshold.setGeometry(QtCore.QRect(10, 150, 421, 101))
        self.groupBox_set_battery_threshold.setObjectName("groupBox_set_battery_threshold")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_set_battery_threshold)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 30, 111, 51))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.checkBox_open = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.checkBox_open.setObjectName("checkBox_open")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.checkBox_open)
        self.checkBox_nap = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.checkBox_nap.setObjectName("checkBox_nap")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.checkBox_nap)
        self.checkBox_exit = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.checkBox_exit.setObjectName("checkBox_exit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.checkBox_exit)
        self.checkBox_pet = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.checkBox_pet.setObjectName("checkBox_pet")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.checkBox_pet)
        self.lineEdit_battery_threshold = QtWidgets.QLineEdit(self.groupBox_set_battery_threshold)
        self.lineEdit_battery_threshold.setEnabled(True)
        self.lineEdit_battery_threshold.setGeometry(QtCore.QRect(130, 40, 21, 20))
        self.lineEdit_battery_threshold.setObjectName("lineEdit_battery_threshold")
        self.horizontalScrollBar_battery_threshold = QtWidgets.QScrollBar(self.groupBox_set_battery_threshold)
        self.horizontalScrollBar_battery_threshold.setEnabled(True)
        self.horizontalScrollBar_battery_threshold.setGeometry(QtCore.QRect(160, 40, 171, 20))
        self.horizontalScrollBar_battery_threshold.setMaximum(100)
        self.horizontalScrollBar_battery_threshold.setProperty("value", 85)
        self.horizontalScrollBar_battery_threshold.setTracking(True)
        self.horizontalScrollBar_battery_threshold.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_battery_threshold.setInvertedAppearance(False)
        self.horizontalScrollBar_battery_threshold.setObjectName("horizontalScrollBar_battery_threshold")
        self.pushButton_set_battery_threshold = QtWidgets.QPushButton(self.groupBox_set_battery_threshold)
        self.pushButton_set_battery_threshold.setGeometry(QtCore.QRect(340, 40, 71, 23))
        self.pushButton_set_battery_threshold.setObjectName("pushButton_set_battery_threshold")
        self.groupBox_exec_result = QtWidgets.QGroupBox(self)
        self.groupBox_exec_result.setGeometry(QtCore.QRect(10, 260, 421, 291))
        self.groupBox_exec_result.setObjectName("groupBox_exec_result")
        self.textEdit_result = QtWidgets.QTextEdit(self.groupBox_exec_result)
        self.textEdit_result.setGeometry(QtCore.QRect(10, 20, 401, 251))
        self.textEdit_result.setObjectName("textEdit_result")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Car", "Form"))
        self.groupBox_device_information.setTitle(_translate("Car", "设备信息"))
        self.groupBox_set_battery_threshold.setTitle(_translate("Car", "设置电量阈值"))
        self.checkBox_open.setText(_translate("Car", "开启"))
        self.checkBox_nap.setText(_translate("Car", "小憩"))
        self.checkBox_exit.setText(_translate("Car", "退出"))
        self.checkBox_pet.setText(_translate("Car", "关怀"))
        self.lineEdit_battery_threshold.setText(_translate("Car", "85"))
        self.pushButton_set_battery_threshold.setText(_translate("Car", "设置"))
        self.groupBox_exec_result.setTitle(_translate("Car", "执行结果"))
