# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qjmsUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow


class Ui_QJMS(QMainWindow):
    def setupUi(self):
        self.setObjectName("QJMS")
        self.resize(445, 614)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(self)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.toolBar.setFont(font)
        self.toolBar.setIconSize(QtCore.QSize(24, 24))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolBar.setObjectName("toolBar")
        self.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_car = QtWidgets.QAction(self)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/c60068129/.designer/file/违规影响类/纯色1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_car.setIcon(icon)
        self.action_car.setObjectName("action_car")
        self.action_wgr = QtWidgets.QAction(self)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/c60068129/.designer/file/违规影响类/纯色2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_wgr.setIcon(icon1)
        self.action_wgr.setObjectName("action_wgr")
        self.toolBar.addAction(self.action_car)
        self.toolBar.addAction(self.action_wgr)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("QJMS", "MainWindow"))
        self.toolBar.setWindowTitle(_translate("QJMS", "toolBar"))
        self.action_car.setText(_translate("QJMS", "car"))
        self.action_car.setToolTip(_translate("QJMS", "car"))
        self.action_wgr.setText(_translate("QJMS", "wgr"))
