# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file 'wgrUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QApplication, QWidget

from wgrSlot import WgrSlot
from wgrUi import Ui_Wgr


class Wgr(Ui_Wgr, WgrSlot):
    def __init__(self):
        super().__init__()
        self.setupUi()

    def setupUi(self):
        super().setupUi()
        self.pushButton_set.clicked.connect(self.set_advance)
        self.pushButton_clearData.clicked.connect(self.clearData)
        self.pushButton_play.clicked.connect(self.play)
        self.pushButton_brake.clicked.connect(self.press_or_release_brake)
        self.pushButton_gears.clicked.connect(self.shift_gears)
        self.horizontalScrollBar_speed.valueChanged.connect(self.get_speed)
        self.pushButton_speed.clicked.connect(self.change_speed)
        self.horizontalScrollBar_battery.valueChanged.connect(self.get_battery)
        self.pushButton_battery.clicked.connect(self.change_battery)
        self.pushButton_screen.clicked.connect(self.chang_screen)
        self.get_devices_informatiion()


if __name__ == '__main__':
    # 实例化，传参
    app = QApplication(sys.argv)
    # 创建ui，引用AutoGenerateUi文件中的Ui_MainWindow类
    ui = Wgr()
    # 创建窗口
    ui.show()
    # 设置窗口名称
    ui.setWindowTitle('QJMS TOOL')
    # 进入程序的主循环，并通过exit函数确保主循环安全结束(该释放资源的一定要释放)
    sys.exit(app.exec_())
